# Generated by Django 4.2.3 on 2023-07-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('find_in_api', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Simulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=4)),
                ('positions', models.PositiveIntegerField()),
                ('tp', models.PositiveIntegerField()),
                ('sl', models.PositiveIntegerField()),
                ('pnl_total_percentage', models.FloatField()),
                ('pnl_total', models.FloatField()),
                ('pnl_average_percentage', models.FloatField()),
                ('pnl_average', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunities_sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY'), ('NONE', 'NONE'), ('OPEN', 'OPEN')], default='NONE', max_length=4)),
                ('stock_rsi', models.BooleanField(default=False)),
                ('macd', models.BooleanField(default=False)),
                ('rsi', models.BooleanField(default=False)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY'), ('NONE', 'NONE'), ('OPEN', 'OPEN')], default='NONE', max_length=4)),
                ('stock_rsi', models.BooleanField(default=False)),
                ('macd', models.BooleanField(default=False)),
                ('rsi', models.BooleanField(default=False)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Open_position_sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='NONE', max_length=4)),
                ('entry_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('open_date', models.DateTimeField()),
                ('srsi', models.FloatField()),
                ('rsi', models.FloatField()),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Open_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='NONE', max_length=4)),
                ('entry_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('leverage', models.PositiveIntegerField()),
                ('margin', models.FloatField()),
                ('id_position', models.PositiveIntegerField()),
                ('open_date', models.DateTimeField()),
                ('take_profit', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Closed_position_sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=4)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('roe', models.FloatField()),
                ('fee', models.FloatField()),
                ('profit', models.FloatField()),
                ('quantity', models.FloatField()),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('srsi_open', models.FloatField()),
                ('rsi_open', models.FloatField()),
                ('srsid_close', models.FloatField(default=None, null=True)),
                ('srsik_close', models.FloatField(default=None, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Closed_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=4)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('roe', models.FloatField()),
                ('fee', models.FloatField()),
                ('profit', models.FloatField()),
                ('profit_after_fee', models.FloatField()),
                ('quantity', models.FloatField()),
                ('leverage', models.PositiveIntegerField()),
                ('margin', models.FloatField()),
                ('id_position', models.PositiveIntegerField()),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('close_method', models.CharField(max_length=10)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Optimum_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=4)),
                ('open_srsi', models.FloatField()),
                ('open_rsi', models.FloatField()),
                ('close_srsi', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbol')),
            ],
            options={
                'unique_together': {('symbol', 'type')},
            },
        ),
    ]
