# Generated by Django 4.2.3 on 2023-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_position_sim',
            name='close_method',
            field=models.FloatField(default=None, null=True),
        ),
    ]
