# Generated by Django 4.2.3 on 2023-07-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_closed_position_sim_close_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closed_position_sim',
            name='close_method',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
