# Generated by Django 4.2.3 on 2023-07-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_closed_position_sim_close_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closed_position_sim',
            old_name='srsid_close',
            new_name='sl',
        ),
        migrations.RenameField(
            model_name='closed_position_sim',
            old_name='srsik_close',
            new_name='tp',
        ),
    ]
