# Generated by Django 4.2.3 on 2023-07-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_srsid_close_closed_position_sim_sl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closed_position_sim',
            old_name='sl',
            new_name='sl_price',
        ),
        migrations.RenameField(
            model_name='closed_position_sim',
            old_name='tp',
            new_name='tp_price',
        ),
        migrations.RemoveField(
            model_name='open_position',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='open_position',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='simulations',
            name='pnl_average_percentage',
        ),
        migrations.AddField(
            model_name='closed_position_sim',
            name='predetermined_tp_sl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='closed_position_sim',
            name='sp_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='closed_position_sim',
            name='tp_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='open_position',
            name='sl_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='open_position',
            name='sp_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='open_position',
            name='tp_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='open_position',
            name='tp_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='open_position_sim',
            name='sl_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='open_position_sim',
            name='tp_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='roe_average',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='roe_total',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='total_fee',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simulations',
            name='pnl_average',
            field=models.FloatField(default=None, null=True),
        ),
    ]
