# Generated by Django 4.2.3 on 2023-09-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_sl_closed_position_sim_sl_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_position_sim',
            name='tp_sl_ratio',
            field=models.FloatField(null=True),
        ),
    ]
