# Generated by Django 4.2.3 on 2023-09-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_closed_position_sim_tp_sl_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_position_sim',
            name='simulation',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
