# Generated by Django 4.2.3 on 2023-09-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_closed_position_sim_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_position_sim',
            name='sl_limit',
            field=models.FloatField(default=None, null=True),
        ),
    ]
