# Generated by Django 4.2.3 on 2023-09-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_closed_position_sim_sl_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_position_sim',
            name='atr',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='closed_position_sim',
            name='ratr',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='open_position_sim',
            name='atr',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='open_position_sim',
            name='ratr',
            field=models.FloatField(default=None, null=True),
        ),
    ]
