# Generated by Django 4.2.3 on 2023-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_closed_position_sim_atr_closed_position_sim_ratr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closed_position_sim',
            old_name='atr',
            new_name='sl_low_limit',
        ),
        migrations.RenameField(
            model_name='simulations',
            old_name='pnl_average',
            new_name='avg_positions_day',
        ),
        migrations.RenameField(
            model_name='simulations',
            old_name='roe_average',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='simulations',
            old_name='roe_total',
            new_name='fee_total',
        ),
        migrations.RenameField(
            model_name='simulations',
            old_name='total_fee',
            new_name='open_rsi',
        ),
        migrations.AlterUniqueTogether(
            name='optimum_parameter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='simulations',
            name='pnl_total',
        ),
        migrations.RemoveField(
            model_name='simulations',
            name='pnl_total_percentage',
        ),
        migrations.RemoveField(
            model_name='simulations',
            name='sl',
        ),
        migrations.RemoveField(
            model_name='simulations',
            name='tp',
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='avg_positions_day',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='criteria',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='duration',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='fee_total',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='pnl',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='positions',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='profit_loss_rate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='sl_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='timeframe',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='tp_sl_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='winning_rate_month',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='winning_rate_week',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='pnl',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='profit_loss_rate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='sl_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='timeframe',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='tp_sl_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='winning_rate_month',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='winning_rate_week',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='open_rsi',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simulations',
            name='positions',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='optimum_parameter',
            unique_together={('symbol', 'type', 'criteria')},
        ),
        migrations.RemoveField(
            model_name='optimum_parameter',
            name='close_srsi',
        ),
        migrations.RemoveField(
            model_name='optimum_parameter',
            name='open_srsi',
        ),
    ]
