# Generated by Django 4.2.3 on 2023-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_srsi_open_closed_position_sim_stoch_open_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulations',
            old_name='winning_rate_month',
            new_name='max_accumulated_loss',
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='losses_in_a_row',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='max_accumulated_loss',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='max_accumulated_profit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='max_pnl',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='min_pnl',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='open_stoch',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='sl_low_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='optimum_parameter',
            name='wins_in_a_row',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='losses_in_a_row',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='max_accumulated_profit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='max_pnl',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='min_pnl',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='open_stoch',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='roe',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='sl_low_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulations',
            name='wins_in_a_row',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
