# Generated by Django 4.2.3 on 2023-09-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_winning_rate_month_simulations_max_accumulated_loss_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optimum_parameter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default=None, max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='optimum_parameter',
            unique_together={('symbol', 'type', 'criteria', 'timeframe')},
        ),
    ]
