# Generated by Django 4.2.3 on 2023-09-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_optimum_parameter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunities',
            name='timeframe',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oportunities',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbol'),
        ),
        migrations.AlterUniqueTogether(
            name='oportunities',
            unique_together={('symbol', 'timeframe')},
        ),
    ]
