# Generated by Django 4.2.3 on 2023-09-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_oportunities_timeframe_alter_oportunities_symbol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closed_position',
            old_name='margin',
            new_name='rsi_open',
        ),
        migrations.RenameField(
            model_name='closed_position',
            old_name='profit_after_fee',
            new_name='stoch_open',
        ),
        migrations.RemoveField(
            model_name='closed_position',
            name='id_position',
        ),
        migrations.RemoveField(
            model_name='closed_position',
            name='leverage',
        ),
        migrations.AddField(
            model_name='closed_position',
            name='sl_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='closed_position',
            name='sl_low_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='closed_position',
            name='sl_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='closed_position',
            name='tp_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='closed_position',
            name='tp_sl_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='closed_position',
            name='close_method',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
