# Generated by Django 4.2.3 on 2023-09-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_margin_closed_position_rsi_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_position',
            name='alt_TP_SL',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='open_position',
            name='alt_TP_SL',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
