# Generated by Django 4.2.3 on 2023-10-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_closed_position_alt_tp_sl_open_position_alt_tp_sl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimum_parameter',
            old_name='winning_rate_week',
            new_name='q',
        ),
    ]
