# Generated by Django 4.2.3 on 2023-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_winning_rate_week_optimum_parameter_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_position',
            name='rsi',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='open_position',
            name='stoch',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='open_position',
            name='stopPrice_precision',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
