# Generated by Django 4.2.3 on 2023-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_open_position_rsi_open_position_stoch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_position',
            name='timeframe',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='open_position',
            name='timeframe',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
