# Generated by Django 4.2.3 on 2023-10-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_closed_position_timeframe_open_position_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_position',
            name='sl_order_id',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default=None, max_length=50, null=True),
        ),
    ]
