# Generated by Django 4.2.3 on 2023-10-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_closed_position_sim_close_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_position_sim',
            name='close_method',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
