# Generated by Django 4.2.3 on 2023-10-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_open_position_tp_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimum_parameter',
            name='factor_ajuste',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
