# Generated by Django 4.2.3 on 2023-11-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_optimum_parameter_factor_ajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimum_parameter',
            name='factor_ajuste',
            field=models.FloatField(default=None, null=True),
        ),
    ]
