# Generated by Django 4.2.3 on 2023-11-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_optimum_parameter_factor_ajuste'),
    ]

    operations = [
    ]
