# Generated by Django 4.2.3 on 2023-12-27 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20231126_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimum_parameter',
            old_name='losses_in_a_row',
            new_name='pnl_av',
        ),
        migrations.RenameField(
            model_name='optimum_parameter',
            old_name='wins_in_a_row',
            new_name='simulation',
        ),
    ]
