# Generated by Django 4.2.3 on 2023-12-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_losses_in_a_row_optimum_parameter_pnl_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimum_parameter',
            name='pnl_av',
            field=models.FloatField(default=None, null=True),
        ),
    ]
