# Generated by Django 4.2.3 on 2023-12-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_optimum_parameter_pnl_av'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimum_parameter',
            name='avg_positions_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='criteria',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='fee_total',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='max_accumulated_loss',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='max_accumulated_profit',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='max_pnl',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='min_pnl',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='open_stoch',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='positions',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='profit_loss_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optimum_parameter',
            name='winning_rate_month',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
