# Generated by Django 4.2.3 on 2023-12-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_optimum_parameter_avg_positions_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_position',
            name='id_position',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
